export const user = {
  name: 'Jessica Harsh',
  avatar100: require('../assets/avatar100.jpeg'),
  avatar50: require('../assets/avatar50.jpeg'),
  trip: 3,
  following: 3,
  followers: 250,
  futureTrips: [
    {
      title: 'Trip title',
      location: 'Location',
      country: 'Country',
      day: '15',
      month: 'July',
      image: require('../assets/trip.jpeg'),
    },
    {
      title: 'Trip title',
      location: 'Location',
      country: 'Country',
      day: '15',
      month: 'July',
      image: require('../assets/trip.jpeg'),
    },
    {
      title: 'Trip title',
      location: 'Location',
      country: 'Country',
      day: '15',
      month: 'July',
      image: require('../assets/trip.jpeg'),
    },
    {
      title: 'Trip title',
      location: 'Location',
      country: 'Country',
      day: '15',
      month: 'July',
      image: require('../assets/trip.jpeg'),
    },
    {
      title: 'Trip title',
      location: 'Location',
      country: 'Country',
      day: '15',
      month: 'July',
      image: require('../assets/trip.jpeg'),
    },
    {
      title: 'Trip title',
      location: 'Location',
      country: 'Country',
      day: '15',
      month: 'July',
      image: require('../assets/trip.jpeg'),
    },
    {
      title: 'Trip title',
      location: 'Location',
      country: 'Country',
      day: '15',
      month: 'July',
      image: require('../assets/trip.jpeg'),
    },
    {
      title: 'Trip title',
      location: 'Location',
      country: 'Country',
      day: '15',
      month: 'July',
      image: require('../assets/trip.jpeg'),
    },
    {
      title: 'Trip title',
      location: 'Location',
      country: 'Country',
      day: '15',
      month: 'July',
      image: require('../assets/trip.jpeg'),
    },
  ],
}
